---
  - name: Create one new IAM user with API keys
    community.aws.iam:
      iam_type: user
      name: "{{ item }}"
      state: present
      password: "97246475674857hgse404a81c4dbebd362fdea6!"
      access_key_state: create
    loop:
      - natalia_user1